# Generated by Django 3.2.2 on 2021-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='departDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
