# Generated by Django 3.2.2 on 2021-05-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_rename_pub_date_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='departDate',
            field=models.DateField(null=True),
        ),
    ]
